name: Smoke Tests

on:
  pull_request:
    branches:
      - main

jobs:
  smoke-test:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Test Repository
        run: git clone --depth=1 https://github.com/anyproto/anytype-test.git .

      - name: Create config.yml file from secret
        run: echo "${{ secrets.CONFIG_YML_CONTENT }}" > config.yml

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Clone anytype-heart with specified branch
        uses: actions/checkout@v4
        with:
          path: mw/anytype-heart

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run smoke tests
        run: npm run test:smoke:testomatio
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          #GH_PAT: ${{ github.token }}
          #GH_KEEP_OUTDATED_REPORTS: 1
          #SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          #SLACK_CHANNEL: 'C07NFB0H5RN'  #test-debugging channel id
